baseurl: /LeanUX
markdown: redcarpet
name: 18F Guide to Lean UX

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18f logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: index.html
  internal: true
- text: 1. Create the Problem Statement
  url: problem-statement/
  internal: true
- text: 2. Declare Assumptions
  url: declare-assumptions/
  internal: true
- text: 3. Prioritize Assumptions, then Build Hypotheses
  url: build-hypotheses/
  internal: true
- text: 4. Select & Break Down Hypotheses
  url: break-down-hypotheses/
  internal: true
- text: 5. Bring into Agile
  url: bring-into-agile/
  internal: true

repos:
- name: LeanUX
  description: Main repository
  url: https://github.com/18F/LeanUX

# Style Variables
brand_color: "#1188ff"
