markdown: redcarpet
name: 18F Guide to Lean UX

exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18f logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction to Lean UX
  url: index.html
  internal: true
- text: Gather your research & create your problem statement
  url: problem-statement/
  internal: true
- text: Declare your Assumptions
  url: declare-assumptions/
  internal: true
- text: Prioritize Assumptions, then Build Hypotheses
  url: build-hypotheses/
  internal: true
- text: Select & Break Down Hypotheses
  url: break-down-hypotheses/
  internal: true
- text: Bring into Agile
  url: bring-into-agile/
  internal: true
- text: Images
  url: images/
  internal: true

repos:
- name: LeanUX
  description: Main repository
  url: https://github.com/18F/LeanUX

defaults:
  -
    scope:
      path: ""
    values:
      layout: "guides_style_18f_default"
